name: "ThreeTierVMSS-APLB-Infra Workflows"

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
      - 'main'
      - 'hotfix/**'

env:
  TF_DIR: environments/dev/
  client-id: ${{ secrets.AZURE_CLIENT_ID }}
  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
permissions:
  id-token: write
  contents: read

jobs:
  terraformInit:
    name: Terraform Init
    runs-on: [self-hosted, ThreeTierVMSS-APLB-Infra]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Azure Login using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ env.client-id }}
        tenant-id: ${{ env.tenant-id }}
        subscription-id: ${{ env.subscription-id }}

    - name: Terraform Init
      id: Init
      run: terraform init -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      working-directory: ${{ env.TF_DIR }}  # Set the working directory to the "terraform-config" folder
    - name: Terraform Fmt
      id: Fmt
      run: terraform fmt 
      continue-on-error: true
      working-directory: .  # Set the working directory to the "terraform-config" folder
      
    - name: Terraform Validate
      id: validate
      run: terraform validate
      working-directory: .  # Set the working directory to the "terraform-config" folder
      
    - name: TFLint
      id: tflint
      continue-on-error: true
      run: |
            tflint --init
            tflint --recursive
    - name: Trivy IaC Scan
      id: trivy
      run: trivy config .
      working-directory: .
      
    - name: Checkov Scan
      id: checkov
      run: checkov -d . --soft-fail
      
    - name: Terraform Plan
      id: plan
      continue-on-error: true
      run: terraform plan -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      working-directory: ${{ env.TF_DIR }}  # Set the working directory for plan

    - name: Terraform Apply
      id: apply
      continue-on-error: true
      run: terraform apply --auto-approve -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      working-directory: ${{ env.TF_DIR }}  # Set the working directory for plan
      
    
